# Generated by Django 2.1.4 on 2021-01-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=300)),
                ('person_email_id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('Message', models.TextField()),
            ],
        ),
    ]
