# Generated by Django 2.1.4 on 2021-02-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accelaration',
            old_name='accelaration_page',
            new_name='page_structure',
        ),
        migrations.RenameField(
            model_name='incubation',
            old_name='incubation_page',
            new_name='page_structure',
        ),
        migrations.RenameField(
            model_name='launchpad',
            old_name='launchpad_page',
            new_name='page_structure',
        ),
    ]
