# Generated by Django 3.0.8 on 2021-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ourstartup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='PressReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stapressRelease/')),
            ],
        ),
        migrations.CreateModel(
            name='StartupSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='startupSession/')),
            ],
        ),
        migrations.AlterField(
            model_name='ourstartup',
            name='image',
            field=models.ImageField(upload_to='startups/'),
        ),
    ]
